# Generated by Django 3.0.5 on 2020-05-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('time', models.CharField(default='00:00', max_length=5)),
                ('booked', models.BooleanField(default=False)),
                ('day_index', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('user_type', models.CharField(default='customer', max_length=24)),
                ('have_booked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marwan_app.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marwan_app.User')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
